
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gerap
 */
public class VentanaPrioridadBicola extends javax.swing.JFrame {
    TDA_Cola obj;
    /**
     * Creates new form VentanaPrioridadBicola
     */
    public VentanaPrioridadBicola() {
        initComponents();
        setLocationRelativeTo(null);
        String t = JOptionPane.showInputDialog(null, "Escribe el tamaño del vector: ");
        obj = new TDA_Cola(Integer.parseInt(t));
        lblMensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextPane();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInsertarini = new javax.swing.JButton();
        btnEliminarFin = new javax.swing.JButton();
        cmbPrioridad = new javax.swing.JComboBox<>();
        lblMensaje = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDato.setBackground(java.awt.Color.cyan);
        txtDato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtMostrar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, java.awt.Color.cyan));
        txtMostrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(txtMostrar);

        btnInsertar.setBackground(java.awt.Color.cyan);
        btnInsertar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(java.awt.Color.cyan);
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnInsertarini.setBackground(java.awt.Color.cyan);
        btnInsertarini.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertarini.setText("Insertar por ini");
        btnInsertarini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertariniActionPerformed(evt);
            }
        });

        btnEliminarFin.setBackground(java.awt.Color.cyan);
        btnEliminarFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarFin.setText("Eliminar por fin");
        btnEliminarFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFinActionPerformed(evt);
            }
        });

        cmbPrioridad.setBackground(java.awt.Color.cyan);
        cmbPrioridad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridad", "1", "2", "3" }));

        lblMensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensaje.setText("MENSAJE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(txtDato, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertarini)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarFin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbPrioridad, 0, 135, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsertar)
                    .addComponent(btnEliminar)
                    .addComponent(btnInsertarini)
                    .addComponent(btnEliminarFin)
                    .addComponent(cmbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblMensaje)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertariniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertariniActionPerformed
        String mensaje = "Selecciona nivel de prioridad";
        if(cmbPrioridad.getSelectedIndex() == 0){
            lblMensaje.setText(mensaje);
            return;
        }
        if(!obj.insertarPorIni(txtDato.getText().charAt(0),cmbPrioridad.getSelectedIndex())){
                mensaje = "Cola llena por INI";
                lblMensaje.setText(mensaje);
        }
        txtDato.setText("");
        cmbPrioridad.setSelectedIndex(0);
        mostrarBicola();
    }//GEN-LAST:event_btnInsertariniActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
       String mensaje = "Selecciona nivel de prioridad";
        if(cmbPrioridad.getSelectedIndex() == 0){
            lblMensaje.setText(mensaje);
            return;
        }
        if(!obj.insertar(txtDato.getText().charAt(0),cmbPrioridad.getSelectedIndex())){
                mensaje = "Cola llena por INI";
                lblMensaje.setText(mensaje);
        }
        txtDato.setText("");
        cmbPrioridad.setSelectedIndex(0);
        mostrarBicola();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEliminarFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFinActionPerformed
        if(!obj.eliminarPorFin()){
            String mensaje = "Cola vacía";
            lblMensaje.setText(mensaje);
            return;
        }
        mostrarBicola();
    }//GEN-LAST:event_btnEliminarFinActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!obj.eliminar()){
            String mensaje = "Cola vacía";
            lblMensaje.setText(mensaje);
            return;
        }
        mostrarBicola();
    }//GEN-LAST:event_btnEliminarActionPerformed
    private void mostrarBicola(){
        String cad = "";
        if (obj.getIni() == -1) {
            txtMostrar.setText("");
            return;
        }
        for (int i = obj.getIni(); i <=obj.getFin(); i++) {
            cad += String.format(" [%d] = [%s] ", i, obj.getValor(i));
        }

        txtMostrar.setText(cad);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrioridadBicola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrioridadBicola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrioridadBicola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrioridadBicola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrioridadBicola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarFin;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertarini;
    private javax.swing.JComboBox<String> cmbPrioridad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtDato;
    private javax.swing.JTextPane txtMostrar;
    // End of variables declaration//GEN-END:variables
}
